// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYyNbz5Y5EemaL1wmun_l1rMqnoJP2YtU',
    appId: '1:956916834979:web:d7bf6a3245a8a841e35516',
    messagingSenderId: '956916834979',
    projectId: 'course-motobike-64406',
    authDomain: 'course-motobike-64406.firebaseapp.com',
    storageBucket: 'course-motobike-64406.appspot.com',
    measurementId: 'G-PQL0SN7NC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO30vVLX-X-Odu9emG1eU5u_6kGMEQWig',
    appId: '1:956916834979:android:c18010b9d6447f46e35516',
    messagingSenderId: '956916834979',
    projectId: 'course-motobike-64406',
    storageBucket: 'course-motobike-64406.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIvOSfaOxn_bSc3TRhsVhEpoWNpJU2PAc',
    appId: '1:956916834979:ios:82eb1ae9ad013c42e35516',
    messagingSenderId: '956916834979',
    projectId: 'course-motobike-64406',
    storageBucket: 'course-motobike-64406.appspot.com',
    iosBundleId: 'com.example.rentMotor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIvOSfaOxn_bSc3TRhsVhEpoWNpJU2PAc',
    appId: '1:956916834979:ios:82eb1ae9ad013c42e35516',
    messagingSenderId: '956916834979',
    projectId: 'course-motobike-64406',
    storageBucket: 'course-motobike-64406.appspot.com',
    iosBundleId: 'com.example.rentMotor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYyNbz5Y5EemaL1wmun_l1rMqnoJP2YtU',
    appId: '1:956916834979:web:7be5f607190d4be8e35516',
    messagingSenderId: '956916834979',
    projectId: 'course-motobike-64406',
    authDomain: 'course-motobike-64406.firebaseapp.com',
    storageBucket: 'course-motobike-64406.appspot.com',
    measurementId: 'G-NB8QD7VSD8',
  );
}
